---
- hosts: nginx
  remote_user: username
  become: yes
  become_method: sudo
  tasks:
    - name: "Install NGINX and MySQL"
      apt: name={{ item }} state=present
      with_items:
        - nginx
        - mysql-server
        - python-mysqldb

    - name: "Start/enable NGINX and MySQL services"
      service: name{{ item }} state=started enabled=yes
      with_items:
        - nginx
        - mysql

    - name: "Create test db"
      mysql_db: name=testdb
                state=present

    - name: "Create new user for cx"
      mysql_user: name=webapp1
                  password=password
                  priv=*.*:ALL state=present
